version: 2

updates:

  - package-ecosystem: bundler
    directory: '/'
    versioning-strategy: increase
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly