daysUntilStale: 60
daysUntilClose: 14
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
exemptProjects: true
closeComment: false
